if(EXISTS "/home/zuchangqu/project/football/engine/tests/build_snapshot/replay_system_test[1]_tests.cmake")
  include("/home/zuchangqu/project/football/engine/tests/build_snapshot/replay_system_test[1]_tests.cmake")
else()
  add_test(replay_system_test_NOT_BUILT replay_system_test_NOT_BUILT)
endif()
