add_test([=[LobbyE2ETest.CreateAndListRooms]=]  /home/zuchangqu/project/football/engine/tests/build_lobby/lobby_e2e_test [==[--gtest_filter=LobbyE2ETest.CreateAndListRooms]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LobbyE2ETest.CreateAndListRooms]=]  PROPERTIES WORKING_DIRECTORY /home/zuchangqu/project/football/engine/tests/build_lobby SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LobbyE2ETest.TwoPlayersJoinRoom]=]  /home/zuchangqu/project/football/engine/tests/build_lobby/lobby_e2e_test [==[--gtest_filter=LobbyE2ETest.TwoPlayersJoinRoom]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LobbyE2ETest.TwoPlayersJoinRoom]=]  PROPERTIES WORKING_DIRECTORY /home/zuchangqu/project/football/engine/tests/build_lobby SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LobbyE2ETest.ChatBetweenPlayers]=]  /home/zuchangqu/project/football/engine/tests/build_lobby/lobby_e2e_test [==[--gtest_filter=LobbyE2ETest.ChatBetweenPlayers]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LobbyE2ETest.ChatBetweenPlayers]=]  PROPERTIES WORKING_DIRECTORY /home/zuchangqu/project/football/engine/tests/build_lobby SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LobbyE2ETest.ReadyUp]=]  /home/zuchangqu/project/football/engine/tests/build_lobby/lobby_e2e_test [==[--gtest_filter=LobbyE2ETest.ReadyUp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LobbyE2ETest.ReadyUp]=]  PROPERTIES WORKING_DIRECTORY /home/zuchangqu/project/football/engine/tests/build_lobby SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  lobby_e2e_test_TESTS LobbyE2ETest.CreateAndListRooms LobbyE2ETest.TwoPlayersJoinRoom LobbyE2ETest.ChatBetweenPlayers LobbyE2ETest.ReadyUp)
