if(EXISTS "/home/zuchangqu/project/football/engine/tests/build_pred/fixed_point_test[1]_tests.cmake")
  include("/home/zuchangqu/project/football/engine/tests/build_pred/fixed_point_test[1]_tests.cmake")
else()
  add_test(fixed_point_test_NOT_BUILT fixed_point_test_NOT_BUILT)
endif()
