if(EXISTS "/home/zuchangqu/project/football/engine/tests/build_pred/frame_sync_performance_test[1]_tests.cmake")
  include("/home/zuchangqu/project/football/engine/tests/build_pred/frame_sync_performance_test[1]_tests.cmake")
else()
  add_test(frame_sync_performance_test_NOT_BUILT frame_sync_performance_test_NOT_BUILT)
endif()
