if(EXISTS "/home/zuchangqu/project/football/engine/tests/build_jitter/frame_sync_coverage_test[1]_tests.cmake")
  include("/home/zuchangqu/project/football/engine/tests/build_jitter/frame_sync_coverage_test[1]_tests.cmake")
else()
  add_test(frame_sync_coverage_test_NOT_BUILT frame_sync_coverage_test_NOT_BUILT)
endif()
