if(EXISTS "/home/zuchangqu/project/football/engine/tests/build_batch2/phase5_test[1]_tests.cmake")
  include("/home/zuchangqu/project/football/engine/tests/build_batch2/phase5_test[1]_tests.cmake")
else()
  add_test(phase5_test_NOT_BUILT phase5_test_NOT_BUILT)
endif()
