if(EXISTS "/home/zuchangqu/project/football/engine/tests/build_batch2/replay_integration_test[1]_tests.cmake")
  include("/home/zuchangqu/project/football/engine/tests/build_batch2/replay_integration_test[1]_tests.cmake")
else()
  add_test(replay_integration_test_NOT_BUILT replay_integration_test_NOT_BUILT)
endif()
