add_test([=[SpectatorTest.Construction]=]  /home/zuchangqu/project/football/engine/tests/build_batch2/spectator_test [==[--gtest_filter=SpectatorTest.Construction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SpectatorTest.Construction]=]  PROPERTIES WORKING_DIRECTORY /home/zuchangqu/project/football/engine/tests/build_batch2 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SpectatorTest.ReceivesFrames]=]  /home/zuchangqu/project/football/engine/tests/build_batch2/spectator_test [==[--gtest_filter=SpectatorTest.ReceivesFrames]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SpectatorTest.ReceivesFrames]=]  PROPERTIES WORKING_DIRECTORY /home/zuchangqu/project/football/engine/tests/build_batch2 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SpectatorTest.NoInputSent]=]  /home/zuchangqu/project/football/engine/tests/build_batch2/spectator_test [==[--gtest_filter=SpectatorTest.NoInputSent]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SpectatorTest.NoInputSent]=]  PROPERTIES WORKING_DIRECTORY /home/zuchangqu/project/football/engine/tests/build_batch2 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SpectatorTest.MultipleSpectators]=]  /home/zuchangqu/project/football/engine/tests/build_batch2/spectator_test [==[--gtest_filter=SpectatorTest.MultipleSpectators]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SpectatorTest.MultipleSpectators]=]  PROPERTIES WORKING_DIRECTORY /home/zuchangqu/project/football/engine/tests/build_batch2 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SpectatorTest.FrameCallback]=]  /home/zuchangqu/project/football/engine/tests/build_batch2/spectator_test [==[--gtest_filter=SpectatorTest.FrameCallback]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SpectatorTest.FrameCallback]=]  PROPERTIES WORKING_DIRECTORY /home/zuchangqu/project/football/engine/tests/build_batch2 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SpectatorTest.StateHashCounted]=]  /home/zuchangqu/project/football/engine/tests/build_batch2/spectator_test [==[--gtest_filter=SpectatorTest.StateHashCounted]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SpectatorTest.StateHashCounted]=]  PROPERTIES WORKING_DIRECTORY /home/zuchangqu/project/football/engine/tests/build_batch2 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  spectator_test_TESTS SpectatorTest.Construction SpectatorTest.ReceivesFrames SpectatorTest.NoInputSent SpectatorTest.MultipleSpectators SpectatorTest.FrameCallback SpectatorTest.StateHashCounted)
